trainingDataMax: 0.0
trainingDataMin: 0.0
inputFunct: ""
trainingDataSize: 333
testingDataSize: 333
numInputNodes: 2
numNodesPerHiddenLayer: 10
numHiddenLayers: 2
numOutputNodes: 1
numEpochs: 40
learningRate: 0.0000000001 # 0.00000000000000000000000005
accuracyThreshold: 0.5 
rateChangeBool: True 