trainingDataMax: 0
trainingDataMin: 0
inputFunct: ""
trainingDataSize: 55
testingDataSize: 55
numInputNodes: 2
numNodesPerHiddenLayer: 10
numHiddenLayers: 2
numOutputNodes: 1
numEpochs: 400 #This Should Eventually be determiend by the script
learningRate: 0.00000025 #This Should Eventually be determiend by the script
accuracyThreshold: 0.99 
rateChangeBool: True #this should eventually be removed when the learning rate is dynamic
