trainingDataMax: 5.0
trainingDataMin: -4.0
inputFunct: "np.pi * var_a"
trainingDataSize: 1000
testingDataSize: 20
numInputNodes: 3
numNodesPerHiddenLayer: 4
numHiddenLayers: 2
numOutputNodes: 1
numEpochs: 10 #This Should Eventually be determiend by the script
learningRate: 0.0000005 #This Should Eventually be determiend by the script
accuracyThreshold: 0.01 
rateChangeBool: True #this should eventually be removed when the learning rate is dynamic