trainingDataMax: 5.0
trainingDataMin: -5.0
inputFunct: "var_a**2 + 0.5*var_b + 0.0*var_c"
trainingDataSize: 150
testingDataSize: 150
numInputNodes: 3
numNodesPerHiddenLayer: 10
numHiddenLayers: 2
numOutputNodes: 1
numEpochs: 100 #This Should Eventually be determiend by the script
learningRate: 0.000005 #This Should Eventually be determiend by the script
accuracyThreshold: 0.1 
rateChangeBool: True #this should eventually be removed when the learning rate is dynamic